apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-todo-list-mongodb-deploy
spec:
  selector:
    matchLabels:
      app: backend-todo-list-mongodb
  template:
    metadata:
      labels:
        app: backend-todo-list-mongodb
    spec:
      containers:
      - name: backend-todo-list-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password123"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-todo-list-mongodb-service
spec:
  selector:
    app: backend-todo-list-mongodb
  ports:
    - port: 27017
      targetPort: 27017