apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-todo-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-todo-list
  template:
    metadata:
      labels:
        app: backend-todo-list
    spec:
      containers:
      - name: backend-todo-list-container
        image: alisaidsm/backend-todo-list:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: backend-todo-list-config
              key: MONGO_URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-todo-list-service
spec:
  type: NodePort
  selector:
    app: backend-todo-list
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000